[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  PNPM_FLAGS = "--no-frozen-lockfile --unsafe-perm=true"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = false
  